2023WS_41114 <br>
Tim Gabriel

<h3>Goal</h3>
<p>I this assignment we learn how to use numpy[1] and refine our knowledge on how to use pandas dataframes[2]. For this we implement a so called loss function[3]. <br>
A loss function is a function that determins the distance between the current output of an algorithm and its expected output.<br>
Our usecase for this is weatherdata collected in Australia and projected in two csv Files.
We implement the lossfunction to internally use a python list and a numpy array. After that we compare which is faster to compute.</p>

<h3>Task 1</h3>
<p>In task 1 we import the provided data into pandas dataframes.<br>
One csv file holds the actual captured weatherdata and the other one holds predicted weatherdata that was calculated with an external formula.</p>

<p>Fist we import the required python libraries:</p>

In [1]:
import numpy as np
import pandas as pd
import timeit #[4]

<p>We save the actual data from "weather_experiment.csv" to a pandas dataframe labelled weather_experiment: </p>

In [2]:
weather_experiment = pd.read_csv("weather_experiment.csv") 
weather_experiment

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,RainToday,RainTomorrow
0,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,48.0,No,No
1,2009-01-02,Cobar,18.4,28.9,0.0,14.8,13.0,37.0,No,No
2,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,46.0,No,No
3,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,31.0,No,No
4,2009-01-06,Cobar,24.2,41.0,0.0,11.2,8.4,35.0,No,No
...,...,...,...,...,...,...,...,...,...,...
55242,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,35.0,No,No
55243,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,37.0,No,No
55244,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,33.0,No,No
55245,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,26.0,No,No
55246,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,30.0,No,No

<p>And we save the predicted data from "weather_prediction.csv" to a pandas dataframe labelled weather_prediction:</p>

In [3]:
weather_prediction = pd.read_csv("weather_prediction.csv") 
weather_prediction

             Date Location  Rainfall Pred.  Evaporation Pred.
0      2009-01-01    Cobar        7.098998           6.179719
1      2009-01-02    Cobar        1.433238           6.375806
2      2009-01-04    Cobar        0.914834           5.687946
3      2009-01-05    Cobar        5.285904           6.897139
4      2009-01-06    Cobar        0.993975           0.050364
...           ...      ...             ...                ...
55242  2017-06-20   Darwin        5.693780           3.400099
55243  2017-06-21   Darwin        1.548031           1.696780
55244  2017-06-22   Darwin        1.516136           2.945245
55245  2017-06-23   Darwin        1.158509           4.960711
55246  2017-06-24   Darwin        1.919091           6.308155

[55247 rows x 4 columns]

<h3>Task 2</h3>
<p>In Task 2 we implement python functions to determine the corresponding lossvalues between the predicted and the actual data. We implement the same function twice. One function uses pythons builtin list to store and return the values and the other one uses numpy arrays.</p>

<h4>Loss Function</h4>
<p>The formula for the loss function is defined as follows[5]: </p>
$$ Loss=\alpha *\left| R^{Pred.}-R^{Exp.}\right| + \beta * \left| E^{Pred.}-E^{Exp.}\right| $$

<h4>Implementation</h4>
<p>First we implement a function that internally uses pythons list to store the data:</p>

In [4]:
def LossAsList(alpha,beta,expected,prediction):
    """ 
    This function determines the lossfunction between predicted
    and recoreded weatherdata.
    It uses a list to store and return the calculated data.
    
    :param alpha: rainfall weighing factor
    :param beta: evaporation weighing factor
    :param expected: a pandas dataframe holding the actual recorded data
    :param prediction: a panadas dataframe holding the predicted data

    :return: a python list where every index is the loss of the corresponding 
             indices between the predicted and actual data. 
                
    """
    if not isinstance(alpha, float):
        raise TypeError('alpha must be provided as a float')
    elif not isinstance(beta, float):
        raise TypeError('beta must be provided as a float')
    elif not isinstance(expected, pd.DataFrame):
        raise TypeError('expected must be provided as a pandas dataframe')
    elif not isinstance(prediction, pd.DataFrame):
        raise TypeError('prediction must be provided as a pandas dataframe')
    
    expectedrain = expected["Rainfall"].tolist()
    expectedevaporation = expected["Evaporation"].tolist()

    predictedrain = prediction["Rainfall Pred."].tolist()
    predictedevaporation = prediction["Evaporation Pred."].tolist()

    loss = []

    for(pred_rain, exp_rain, pred_eva, exp_eva) in \
        zip(predictedrain, expectedrain, predictedevaporation, expectedevaporation):
        
        currentloss = alpha * abs(pred_rain - exp_rain) + beta * abs(pred_eva - exp_eva)
        loss.append(currentloss)
    return loss

<p>After that we implemet the same function again, but now it uses a numpy array to store the data:</p>

In [5]:
def LossAsNP(alpha,beta,expected,prediction):
    """ 
    This function determines the lossfunction between predicted
    and recoreded weatherdata.
    It uses a numpy array to store and return the calculated data.
    
    :param alpha: rainfall weighing factor
    :param beta: evaporation weighing factor
    :param expected: a pandas dataframe holding the actual recorded data
    :param prediction: a panadas dataframe holding the predicted data

    :return: a numpy array where every index is the loss of the corresponding 
             indices between the predicted and actual data. 
                
    """
    if not isinstance(alpha, float):
        raise TypeError('alpha must be provided as a float')
    elif not isinstance(beta, float):
        raise TypeError('beta must be provided as a float')
    elif not isinstance(expected, pd.DataFrame):
        raise TypeError('expected must be provided as a pandas dataframe')
    elif not isinstance(prediction, pd.DataFrame):
        raise TypeError('prediction must be provided as a pandas dataframe')
        
    expectedrain = expected["Rainfall"].to_numpy()
    expectedevaporation = expected["Evaporation"].to_numpy()

    predictedrain = prediction["Rainfall Pred."].to_numpy()
    predictedevaporation = prediction["Evaporation Pred."].to_numpy()
    
    loss = alpha * np.abs(predictedrain - expectedrain) + \
           beta * np.abs(predictedevaporation - expectedevaporation)
    return loss

<h3>Task 3</h3>
<p>In task 3 we run both of our functions and time how long they take for 100 iterations. Then we compare which implementation is faster: The python list or the numpy array.</p>

<h4>Constants</h4>
<p>For this we need to assign values to the weighing factors Î± and Î². These are project specific and were given to us in the assignement paper.<br>
We define them as follows:
$$\alpha =0.5$$
$$\beta =0.5$$
</p>

In [6]:
alpha = 0.5
beta = 0.5

<h4>Computing our data</h4>
<p>Now that we have all the data we need, we can use our functions to determine the speed difference between both implementations.<br>
For this we use pythons builtin module timeit. We run 100 iterations of our functions and print the resulting time it took to compute:</p>

In [7]:
ListTime = timeit.timeit(lambda:LossAsList(alpha,beta,weather_experiment,weather_prediction), number=100)
NPArrayTime = timeit.timeit(lambda:LossAsNP(alpha,beta,weather_experiment,weather_prediction), number=100)

print(f"The List implementation finished after {ListTime} seconds.")
print(f"The Numpy implementation finished after {NPArrayTime} seconds.")

The List implementation finished after 2.682304000016302 seconds.
The Numpy implementation finished after 0.03079329989850521 seconds.

In [8]:
times=[ListTime, NPArrayTime]
mintime = min(times)
maxtime = max(times)

difference = maxtime/mintime

if mintime==ListTime:
    print(f"The List implementation is {difference} times faster than the Numpy implementation.")
else:
    print(f"The Numpy implementation is {difference} times faster than the List implementation.")

The Numpy implementation is 87.10674103968013 times faster than the List implementation.

<h3>Conclusion</h3>
<p>In this assignment we learned what a loss function is and how to use pythons builtin timeit library. We also strengthened our knowledge of pythons pandas library.
<br>
The results of our testing show that Numpy is magnitudes faster than pythons list and that it should be favored whenever possible.
</p>

<h3>References</h3>
<ol>
<li>NumPy Developers "NumPy documentation".<br> Published 2008 <br> https://numpy.org/doc/stable/ <br> Accessed December 12th, 2023</li>
<li>pandas "pandas documentation".<br> Last updated on Nov 10, 2023<br> https://pandas.pydata.org/docs/ <br>Accessed December 12th, 2023</li>
<li>Christophe Pere "What are Loss Functions?"<br> Published Jun 17, 2020 <br> https://towardsdatascience.com/what-is-loss-function-1e2605aeb904 <br>Accessed December 12th, 2023
</li>
<li>Python Software Foundation "timeit â€” Measure execution time of small code snippets".<br>Last updated on Dec 01, 2023 <br> https://docs.python.org/3/library/timeit.html <br>Accessed December 12th, 2023  </li>
<li>Zyba Ltd, "Equation Editor for online mathematics".<br> Published 2005 <br> https://editor.codecogs.com/<br>Accessed December 12th, 2023
</li>



</ol>